[token.NAM]
# this always needs to be present for our tooling to work
tpknam1qzvszv50azclqa05reqveehkwknpl4kh6tn3vajpt0vusa8mjpluk89ac03 = "1000000"
tpknam1qqu944gyy0unek5vpawft46rz0aj7u4zjv5lged60pn6gg8azdg5kvusuz8 = "1230000"

tnam1q8nzq9m5v8upn6jkjsljf25mzf2n9u7qfyc8kwje = "100000"
tnam1q9t889stlm2y86vpwvglwagyqdpfe48rmcwggq2r = "100000"
tnam1q9tn563pzl9dtwv7nqqaf7p8pcfrfyvxm5ahsu7h = "100000"
